//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongsAlbum
    {
        public int Id { get; set; }
        public int SongsId { get; set; }
        public int AlbumsId { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Song Song { get; set; }
    }
}
