-- MySQL Script generated by MySQL Workbench
-- 10/09/15 23:57:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dictionary
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dictionary` ;

-- -----------------------------------------------------
-- Schema dictionary
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dictionary` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `dictionary` ;

-- -----------------------------------------------------
-- Table `languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `languages` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `languages` (
  `id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `words`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `words` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `words` (
  `id` INT NOT NULL COMMENT '',
  `word` VARCHAR(45) NULL COMMENT '',
  `language_id` INT NULL COMMENT '',
  `words_id` INT NOT NULL COMMENT '',
  `words_id1` INT NOT NULL COMMENT '',
  `explanations_id` INT NOT NULL COMMENT '',
  `languages_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `synonyms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `synonyms` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `synonyms` (
  `id` INT NOT NULL COMMENT '',
  `words_id` INT NOT NULL COMMENT '',
  `syn_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `explanations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `explanations` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `explanations` (
  `id` INT NOT NULL COMMENT '',
  `desc` VARCHAR(45) NULL COMMENT '',
  `words_id` INT NOT NULL COMMENT '',
  `languages_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `translation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `translation` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `translation` (
  `id` INT NOT NULL COMMENT '',
  `words_id` INT NOT NULL COMMENT '',
  `traslation_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
